Tucker/revise release process
omnivector-solutions/jobbergate-cli pull request #85
Opened 2021-10-15 00:15 UTC by dusktreader

2021-10-15 00:30 UTC, jamesbeedy commented on scripts/release.sh
> +git add pyproject.toml CHANGELOG.rst
these are the only files that are modified when a release is created and the changelog is updated

2021-10-15 12:01 UTC, zsinx6 requested changes

2021-10-15 12:01 UTC, zsinx6 commented on pyproject.toml
> +version = "1.4.7"
Are the name and version correct? Should not be jobbergate-cli and the version match the one in the chabgelog?

2021-10-15 13:33 UTC, heitorPB commented on README.rst
> +   make release-<scope>
```suggestion
.. code-block:: console

   make release-<scope>
```

RST requires an empty line there. It breaks sphins otherwise.

2021-10-15 13:34 UTC, heitorPB commented on README.rst
> +* [MIT](LICENSE)
```suggestion

* `MIT <LICENSE>`_.
```

2021-10-15 13:34 UTC, heitorPB commented on README.rst
> +* Copyright (c) 2020 OmniVector Solutions <admin@omnivector.solutions>
```suggestion

* Copyright (c) 2020-2021 OmniVector Solutions <admin@omnivector.solutions>
```

2021-10-15 21:47 UTC, dusktreader commented on scripts/release.sh
> +git add pyproject.toml CHANGELOG.rst
The pyproject.toml contains the version metadata that is bumped by the release script via:
`poetry version <type>`

2021-10-15 21:49 UTC, dusktreader commented on Makefile
> +clean: clean-eggs clean-build
Thanks. Some bad copy pasta there

2021-10-15 21:51 UTC, dusktreader commented on README.rst
> +You should ensure that the snap builds successfully and uploads
Excellent. Will do

2021-10-20 11:17 UTC, heitorPB commented on jobbergate_cli/jobberappslib.py
> +    """Returns a list of inputfiles in a directory ( default: pwd)"""
```suggestion
    """Returns a list of input files in a directory (default: pwd)."""
```

2021-10-20 22:40 UTC, zsinx6 approved these changes

2021-10-26 17:26 UTC, merged